# Generated by Django 4.1.5 on 2023-01-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
